                        <!-- BEGIN #localpages -->
                        <div id="localpages" class="container padding-vert-lg font-16 bordered--top bordered--gray0">
                            <div class="row bordered--bottom bordered--gray0">
                                <div class="col-xs-12 col-md-3">
                                    <h2 class="font-14 lh-standard"><span class="font--600">Sears Hometown Store</span><div class="font--400"><span>11 E Marketview Drive</span><br><span>Champaign</span>, <span>IL</span>&nbsp;<span>61820</span><br>  <span>Phone:</span> &nbsp;<span>(217) 355-3125</span><br><br>  <span class="font--dark">Store is currently closed</span>  <br><br><div> Store Hours: <div>Mon: 10:00 am - 8:00 pm </div><div>Tue: 10:00 am - 8:00 pm </div><div>Wed: 10:00 am - 8:00 pm </div><div>Thu: 10:00 am - 8:00 pm </div><div>Fri: 10:00 am - 8:00 pm </div><div>Sat: 10:00 am - 8:00 pm </div><div>Sun: 11:00 am - 4:00 pm </div></div><br><br><a href="https://www.facebook.com/SearsHTSChampaignIL" target="_blank"><i class="fa fa-facebook-square font--facebook font-21"></i></a> &nbsp; <a href="https://plus.google.com/101554006142545029860" target="_blank"><i class="fa fa-google-plus-square font--googlePlus font-21"></i></a></div><div itemscope="" itemtype="http://schema.org/LocalBusiness" class="hide"><h1><span itemprop="name">Sears Hometown Store</span></h1><span itemprop="description"></span><div itemprop="address" itemscope="" itemtype="http://schema.org/PostalAddress"><span itemprop="streetAddress">11 E Marketview Drive</span><span itemprop="addressLocality">Champaign</span>, <span itemprop="addressRegion">IL</span><span itemprop="postalCode">61820</span><span itemprop="addressCountry">US</span></div><div itemprop="image" itemscope="" itemtype="http://schema.org/ImageObject"><img src="//www.searshometownstores.com/c.3721178/hometown/img/hts_header.png" itemprop="url"></div><span itemprop="telephone">(217) 355-3125</span><div itemprop="geo" itemscope="" itemtype="http://schema.org/GeoCoordinates"><meta itemprop="latitude" content="40.1374547"><meta itemprop="longitude" content="-88.2422519"></div><time itemprop="openingHours" datetime="Mo 10:00 am-8:00 pm"></time><time itemprop="openingHours" datetime="Tu 10:00 am-8:00 pm"></time><time itemprop="openingHours" datetime="We 10:00 am-8:00 pm"></time><time itemprop="openingHours" datetime="Th 10:00 am-8:00 pm"></time><time itemprop="openingHours" datetime="Fr 10:00 am-8:00 pm"></time><time itemprop="openingHours" datetime="Sa 10:00 am-8:00 pm"></time><time itemprop="openingHours" datetime="Su 11:00 am-4:00 pm"></time></div></h2></div>
                                <div class="col-xs-12 col-md-9 local-store-on-page-text font--400 font-14">Owned and operated by a member of your community, Sears Hometown Stores have been serving customers for over 24 years. As licensees of the Sears brand, these independent business owners, control their own destiny and will be here for years to come. They are here to bring you great prices on the quality appliances, tools and lawn &amp; garden equipment you are looking for, without sacrificing the knowledge and expertise you are familiar with from smaller businesses. Shopping at a Sears Hometown Stores Franchise means supporting your local community members, who are here to bring you nothing short of the best.</div>
                            </div>
                        </div>
                        <!-- END #localpages -->
