                        <!-- BEGIN #merchantPick2 (product slider) -->
                        <aside id="merchantsPick2" class="container padding-vert-xl bordered--top bordered--gray0">
                            <!-- TEMPLATE STARTS: n-->
                            <aside class="top-deals-items" style="position: relative;">
                                <h2 class="font--400 padding-vert-md">Top Deals</h2>
                                <div class="merchaPicksRotator owl-carousel owl-theme owl-loaded owl-drag">
                                    <div class="owl-stage-outer">
                                        <div class="owl-stage" style="transform: translate3d(-543px, 0px, 0px); transition: 0s; width: 2174px;">
                                            <div class="owl-item cloned" style="width: 108.667px;">
                                                <div class="merchants-picks-item-wrap">
                                                    <div itemprop="itemListElement" data-item-id="147665" data-track-productlist-list="" data-track-productlist-category="" data-track-productlist-position="" data-sku="022083483000" class="itemWrap padding-horiz-sm"><a href="//product/Samsung-NE59N6630SSAA-59-cu-ft-Freestanding-Electric-Range-with-True-Convection-Stainless-Steel?preview=4877" data-touchpoint="home" data-hashtag="#/product/Samsung-NE59N6630SSAA-59-cu-ft-Freestanding-Electric-Range-with-True-Convection-Stainless-Steel?preview=4877"><img data-src="//c.shld.net/rpx/i/s/i/spin/10103564/prod_19256412412?hei=200&amp;wid=200&amp;sharpen=1" alt="022083483000 Samsung NE59N6630SS/AA 5.9 cu. ft. Freestanding Electri" class="owl-lazy img-responsive" style="opacity: 1"><br>  <div class="font-18 margin-top5" data-view="Global.StarRating"><!-- TEMPLATE STARTS: n-->
<span data-validation="control-group" class="global-columnAttributes">   <span class="text-center" data-toggle="rater" data-validation="control" data-name="" data-max="5" data-value="0">   </span>   <strong class="metaRatingValueForIndividualReviews bg--primary font--light padding--sm border-radius--xl hide">0</strong>   </span> 
<!-- TEMPLATE ENDS: n --></div><br class="clear">  <div class="itemTitle font-14 lh-sm block-with-text"><span class="font--600 font--dark font-spacing-1">Samsung NE59N6630SS/AA 5.9 cu. ft. Freestanding Electric Range with True Convection -Stainless Stee</span></div><div class="itemPrice"><div data-view="Item.Price"><!-- TEMPLATE STARTS: n-->
 <div class="item-views-price">   <span itemprop="offers" itemscope="" itemtype="http://schema.org/Offer"><link itemprop="availability" href="http://schema.org/OutOfStock"><link itemprop="itemCondition" href="http://schema.org/NewCondition">   <meta itemprop="priceCurrency" content="USD">  <div class="font-12 font--gray1"><span>   <del>$999.99</del>   (List Price) </span></div>   <div class="btn-show-price"><meta itemprop="priceCurrency" content="USD"><meta itemprop="price" content="749.99"><strong class="font--black price-font" data-rate="749.99">  $749.99  </strong>   <span class="font-black plp--title font-14 lh-sm font--text block-with-text">or</span>      <strong data-placement="top" data-toggle="tooltip" title="" data-original-title="To get the leasing price, add the item to your cart and select the 'Lease It' option to checkout">$33.75/week</strong>    </div>       <p class="font-14 font--green block-with-text-1 hidden-xs hidden-sm"><span>You Save: &nbsp;</span><span class="font--green font--600">$250.00</span></p>       </span>    </div> 
<!-- TEMPLATE ENDS: n --></div></div></a><span class="add-to-shopping-list-container padding-vert-md"><button class="btn btn-link bordered--xs bordered--gray2 bg--gray0" data-toggle="tooltip" title="" style="display: none;" data-action="go-to-shopping-list" data-item-id="147665" data-original-title="View shopping list"><i class="fa fa-th-list font--dark" aria-hidden="true"></i></button></span></div>
                                                </div>
                                            </div>
                                            <div class="owl-item cloned" style="width: 108.667px;">
                                                <div class="merchants-picks-item-wrap">
                                                    <div itemprop="itemListElement" data-item-id="20617" data-track-productlist-list="" data-track-productlist-category="" data-track-productlist-position="" data-sku="026025132000" class="itemWrap padding-horiz-sm"><a href="//product/Kenmore-25132-43-cu-ft-Top-Load-Washer-w-Exclusive-Triple-Action-Impeller-White?preview=4877" data-touchpoint="home" data-hashtag="#/product/Kenmore-25132-43-cu-ft-Top-Load-Washer-w-Exclusive-Triple-Action-Impeller-White?preview=4877"><img data-src="//c.shld.net/rpx/i/s/i/spin/10130653/prod_18983787712?hei=200&amp;wid=200&amp;sharpen=1" alt="026025132000 Kenmore 25132  4.3 cu. ft. Top Load Washer w/ Exclusive" class="owl-lazy img-responsive" style="opacity: 1"><br>  <div class="font-18 margin-top5" data-view="Global.StarRating"><!-- TEMPLATE STARTS: n-->
<span data-validation="control-group" class="global-columnAttributes">   <span class="text-center" data-toggle="rater" data-validation="control" data-name="" data-max="5" data-value="3.5">   </span>   <div class="global-views-star-rating-area font--review itemReview" data-toggle="rater" data-validation="control" data-name="" data-max="5" data-value="3.5">  <div class="global-views-star-rating-area-empty font--review itemReview"><div class="global-views-star-rating-area-empty-content"> <i class="fa fa-star-o"></i><i class="fa fa-star-o"></i><i class="fa fa-star-o"></i><i class="fa fa-star-o"></i><i class="fa fa-star-o"></i> </div></div>  <div class="global-views-star-rating-area-fill font--review itemReview" data-toggle="ratting-component-fill" style="width: 70%"><div class="global-views-star-rating-area-filled"> <i class="fa fa-star"></i><i class="fa fa-star"></i><i class="fa fa-star"></i><i class="fa fa-star"></i><i class="fa fa-star"></i> </div></div></div>   </span> 
<!-- TEMPLATE ENDS: n --></div><br class="clear">  <div class="itemTitle font-14 lh-sm block-with-text"><span class="font--600 font--dark font-spacing-1">Kenmore 25132  4.3 cu. ft. Top Load Washer w/ Exclusive Triple Action Impeller - White</span></div><div class="itemPrice"><div data-view="Item.Price"><!-- TEMPLATE STARTS: n-->
 <div class="item-views-price">   <span itemprop="offers" itemscope="" itemtype="http://schema.org/Offer"><link itemprop="availability" href="http://schema.org/OutOfStock"><link itemprop="itemCondition" href="http://schema.org/NewCondition">   <meta itemprop="priceCurrency" content="USD">  <div class="font-12 font--gray1"><span>   <del>$839.99</del>   (List Price) </span></div>   <div class="btn-show-price"><meta itemprop="priceCurrency" content="USD"><meta itemprop="price" content="579.99"><strong class="font--black price-font" data-rate="579.99">  $579.99  </strong>   <span class="font-black plp--title font-14 lh-sm font--text block-with-text">or</span>      <strong data-placement="top" data-toggle="tooltip" title="" data-original-title="To get the leasing price, add the item to your cart and select the 'Lease It' option to checkout">$26.10/week</strong>    </div>       <p class="font-14 font--green block-with-text-1 hidden-xs hidden-sm"><span>You Save: &nbsp;</span><span class="font--green font--600">$260.00</span></p>       </span>    </div> 
<!-- TEMPLATE ENDS: n --></div></div></a><span class="add-to-shopping-list-container padding-vert-md"><button class="btn btn-link bordered--xs bordered--gray2 bg--gray0" data-toggle="tooltip" title="" style="display: none;" data-action="go-to-shopping-list" data-item-id="20617" data-original-title="View shopping list"><i class="fa fa-th-list font--dark" aria-hidden="true"></i></button></span></div>
                                                </div>
                                            </div>
                                            <div class="owl-item cloned" style="width: 108.667px;">
                                                <div class="merchants-picks-item-wrap">
                                                    <div itemprop="itemListElement" data-item-id="20618" data-track-productlist-list="" data-track-productlist-category="" data-track-productlist-position="" data-sku="026065132000" class="itemWrap padding-horiz-sm"><a href="//product/Kenmore-65132-70-cu-ft-Electric-Dryer-w-SmartDry-Plus-Technology-White?preview=4877" data-touchpoint="home" data-hashtag="#/product/Kenmore-65132-70-cu-ft-Electric-Dryer-w-SmartDry-Plus-Technology-White?preview=4877"><img data-src="//c.shld.net/rpx/i/s/i/spin/10130653/prod_12126198612?hei=200&amp;wid=200&amp;sharpen=1" alt="026065132000 Kenmore 65132  7.0 cu. ft. Electric Dryer w/ SmartDry P" class="owl-lazy img-responsive" style="opacity: 1"><br>  <div class="font-18 margin-top5" data-view="Global.StarRating"><!-- TEMPLATE STARTS: n-->
<span data-validation="control-group" class="global-columnAttributes">   <span class="text-center" data-toggle="rater" data-validation="control" data-name="" data-max="5" data-value="4">   </span>   <div class="global-views-star-rating-area font--review itemReview" data-toggle="rater" data-validation="control" data-name="" data-max="5" data-value="4">  <div class="global-views-star-rating-area-empty font--review itemReview"><div class="global-views-star-rating-area-empty-content"> <i class="fa fa-star-o"></i><i class="fa fa-star-o"></i><i class="fa fa-star-o"></i><i class="fa fa-star-o"></i><i class="fa fa-star-o"></i> </div></div>  <div class="global-views-star-rating-area-fill font--review itemReview" data-toggle="ratting-component-fill" style="width: 80%"><div class="global-views-star-rating-area-filled"> <i class="fa fa-star"></i><i class="fa fa-star"></i><i class="fa fa-star"></i><i class="fa fa-star"></i><i class="fa fa-star"></i> </div></div></div>   </span> 
<!-- TEMPLATE ENDS: n --></div><br class="clear">  <div class="itemTitle font-14 lh-sm block-with-text"><span class="font--600 font--dark font-spacing-1">Kenmore 65132  7.0 cu. ft. Electric Dryer w/ SmartDry Plus Technology - White</span></div><div class="itemPrice"><div data-view="Item.Price"><!-- TEMPLATE STARTS: n-->
 <div class="item-views-price">   <span itemprop="offers" itemscope="" itemtype="http://schema.org/Offer"><link itemprop="availability" href="http://schema.org/OutOfStock"><link itemprop="itemCondition" href="http://schema.org/NewCondition">   <meta itemprop="priceCurrency" content="USD">  <div class="font-12 font--gray1"><span>   <del>$839.99</del>   (List Price) </span></div>   <div class="btn-show-price"><meta itemprop="priceCurrency" content="USD"><meta itemprop="price" content="579.99"><strong class="font--black price-font" data-rate="579.99">  $579.99  </strong>   <span class="font-black plp--title font-14 lh-sm font--text block-with-text">or</span>      <strong data-placement="top" data-toggle="tooltip" title="" data-original-title="To get the leasing price, add the item to your cart and select the 'Lease It' option to checkout">$26.10/week</strong>    </div>       <p class="font-14 font--green block-with-text-1 hidden-xs hidden-sm"><span>You Save: &nbsp;</span><span class="font--green font--600">$260.00</span></p>       </span>    </div> 
<!-- TEMPLATE ENDS: n --></div></div></a><span class="add-to-shopping-list-container padding-vert-md"><button class="btn btn-link bordered--xs bordered--gray2 bg--gray0" data-toggle="tooltip" title="" style="display: none;" data-action="go-to-shopping-list" data-item-id="20618" data-original-title="View shopping list"><i class="fa fa-th-list font--dark" aria-hidden="true"></i></button></span></div>
                                                </div>
                                            </div>
                                            <div class="owl-item cloned" style="width: 108.667px;">
                                                <div class="merchants-picks-item-wrap">
                                                    <div itemprop="itemListElement" data-item-id="134625" data-track-productlist-list="" data-track-productlist-category="" data-track-productlist-position="" data-sku="071075277000" class="itemWrap padding-horiz-sm"><a href="//product/Craftsman-020698-2700psi-21-GPM-Gas-Pressure-Washer?preview=4877" data-touchpoint="home" data-hashtag="#/product/Craftsman-020698-2700psi-21-GPM-Gas-Pressure-Washer?preview=4877"><img data-src="//c.shld.net/rpx/i/s/i/spin/10047173/prod_19101262412?hei=200&amp;wid=200&amp;sharpen=1" alt="071075277000 Craftsman 020698 2700psi 2.1 GPM Gas Pressure Washer" class="owl-lazy img-responsive" style="opacity: 1"><br>  <div class="font-18 margin-top5" data-view="Global.StarRating"><!-- TEMPLATE STARTS: n-->
<span data-validation="control-group" class="global-columnAttributes">   <span class="text-center" data-toggle="rater" data-validation="control" data-name="" data-max="5" data-value="0">   </span>   <strong class="metaRatingValueForIndividualReviews bg--primary font--light padding--sm border-radius--xl hide">0</strong>   </span> 
<!-- TEMPLATE ENDS: n --></div><br class="clear">  <div class="itemTitle font-14 lh-sm block-with-text"><span class="font--600 font--dark font-spacing-1">Craftsman 020698 2700psi 2.1 GPM Gas Pressure Washer</span></div><div class="itemPrice"><div data-view="Item.Price"><!-- TEMPLATE STARTS: n-->
 <div class="item-views-price">   <span itemprop="offers" itemscope="" itemtype="http://schema.org/Offer"><link itemprop="availability" href="http://schema.org/OutOfStock"><link itemprop="itemCondition" href="http://schema.org/NewCondition">   <meta itemprop="priceCurrency" content="USD">  <div class="font-12 font--gray1"><span>   <del>$369.99</del>   (List Price) </span></div>   <div class="btn-show-price"><meta itemprop="priceCurrency" content="USD"><meta itemprop="price" content="299.99"><strong class="font--black price-font" data-rate="299.99">  $299.99  </strong>   <span class="font-black plp--title font-14 lh-sm font--text block-with-text">or</span>      <strong data-placement="top" data-toggle="tooltip" title="" data-original-title="To get the leasing price, add the item to your cart and select the 'Lease It' option to checkout">$13.50/week</strong>    </div>       <p class="font-14 font--green block-with-text-1 hidden-xs hidden-sm"><span>You Save: &nbsp;</span><span class="font--green font--600">$70.00</span></p>       </span>    </div> 
<!-- TEMPLATE ENDS: n --></div></div></a><span class="add-to-shopping-list-container padding-vert-md"><button class="btn btn-link bordered--xs bordered--gray2 bg--gray0" data-toggle="tooltip" title="" style="display: none;" data-action="go-to-shopping-list" data-item-id="134625" data-original-title="View shopping list"><i class="fa fa-th-list font--dark" aria-hidden="true"></i></button></span></div>
                                                </div>
                                            </div>
                                            <div class="owl-item cloned" style="width: 108.667px;">
                                                <div class="merchants-picks-item-wrap">
                                                    <div itemprop="itemListElement" data-item-id="12047" data-track-productlist-list="" data-track-productlist-category="" data-track-productlist-position="" data-sku="009031794000" class="itemWrap padding-horiz-sm"><a href="//product/Craftsman-31794-17-pc-Screwdriver-Set?preview=4877" data-touchpoint="home" data-hashtag="#/product/Craftsman-31794-17-pc-Screwdriver-Set?preview=4877"><img data-src="//c.shld.net/rpx/i/s/i/spin/image/spin_prod_1159448512?hei=200&amp;wid=200&amp;sharpen=1" alt="009031794000 Craftsman 17 pc. Screwdriver Set" class="owl-lazy img-responsive" style="opacity: 1"><br>  <div class="font-18 margin-top5" data-view="Global.StarRating"><!-- TEMPLATE STARTS: n-->
<span data-validation="control-group" class="global-columnAttributes">   <span class="text-center" data-toggle="rater" data-validation="control" data-name="" data-max="5" data-value="5">   </span>   <div class="global-views-star-rating-area font--review itemReview" data-toggle="rater" data-validation="control" data-name="" data-max="5" data-value="5">  <div class="global-views-star-rating-area-empty font--review itemReview"><div class="global-views-star-rating-area-empty-content"> <i class="fa fa-star-o"></i><i class="fa fa-star-o"></i><i class="fa fa-star-o"></i><i class="fa fa-star-o"></i><i class="fa fa-star-o"></i> </div></div>  <div class="global-views-star-rating-area-fill font--review itemReview" data-toggle="ratting-component-fill" style="width: 100%"><div class="global-views-star-rating-area-filled"> <i class="fa fa-star"></i><i class="fa fa-star"></i><i class="fa fa-star"></i><i class="fa fa-star"></i><i class="fa fa-star"></i> </div></div></div>   </span> 
<!-- TEMPLATE ENDS: n --></div><br class="clear">  <div class="itemTitle font-14 lh-sm block-with-text"><span class="font--600 font--dark font-spacing-1">Craftsman 31794 17 pc. Screwdriver Set</span></div><div class="itemPrice"><div data-view="Item.Price"><!-- TEMPLATE STARTS: n-->
 <div class="item-views-price">   <span itemprop="offers" itemscope="" itemtype="http://schema.org/Offer"><link itemprop="availability" href="http://schema.org/OutOfStock"><link itemprop="itemCondition" href="http://schema.org/NewCondition">   <meta itemprop="priceCurrency" content="USD">  <div class="font-12 font--gray1"><span>   <del>$34.99</del>   (List Price) </span></div>   <div class="btn-show-price"><meta itemprop="priceCurrency" content="USD"><meta itemprop="price" content="29.99"><strong class="font--black price-font" data-rate="29.99">  $29.99  </strong>     </div>       <p class="font-14 font--green block-with-text-1 hidden-xs hidden-sm"><span>You Save: &nbsp;</span><span class="font--green font--600">$5.00</span></p>       </span>    </div> 
<!-- TEMPLATE ENDS: n --></div></div></a><span class="add-to-shopping-list-container padding-vert-md"><button class="btn btn-link bordered--xs bordered--gray2 bg--gray0" data-toggle="tooltip" title="" style="display: none;" data-action="go-to-shopping-list" data-item-id="12047" data-original-title="View shopping list"><i class="fa fa-th-list font--dark" aria-hidden="true"></i></button></span></div>
                                                </div>
                                            </div>
                                            <div class="owl-item active" style="width: 108.667px;">
                                                <div class="merchants-picks-item-wrap">
                                                    <div itemprop="itemListElement" data-item-id="88120" data-track-productlist-list="" data-track-productlist-category="" data-track-productlist-position="" data-sku="026020232000" class="itemWrap padding-horiz-sm"><a href="//product/Kenmore-20232-35-cu-ft-TopLoad-Washer-with-Deep-Fill-Option-White?preview=4877" data-touchpoint="home" data-hashtag="#/product/Kenmore-20232-35-cu-ft-TopLoad-Washer-with-Deep-Fill-Option-White?preview=4877"><img data-src="//c.shld.net/rpx/i/s/i/spin/10130653/prod_16327306112?hei=200&amp;wid=200&amp;sharpen=1" alt="026020232000 Kenmore 20232  3.5 cu. ft. Top-Load Washer with Deep Fi" class="owl-lazy img-responsive" style="opacity: 1" src="//c.shld.net/rpx/i/s/i/spin/10130653/prod_16327306112?hei=200&amp;wid=200&amp;sharpen=1"><br>  <div class="font-18 margin-top5" data-view="Global.StarRating"><!-- TEMPLATE STARTS: n-->
<span data-validation="control-group" class="global-columnAttributes">   <span class="text-center" data-toggle="rater" data-validation="control" data-name="" data-max="5" data-value="4">   </span>   <div class="global-views-star-rating-area font--review itemReview" data-toggle="rater" data-validation="control" data-name="" data-max="5" data-value="4">  <div class="global-views-star-rating-area-empty font--review itemReview"><div class="global-views-star-rating-area-empty-content"> <i class="fa fa-star-o"></i><i class="fa fa-star-o"></i><i class="fa fa-star-o"></i><i class="fa fa-star-o"></i><i class="fa fa-star-o"></i> </div></div>  <div class="global-views-star-rating-area-fill font--review itemReview" data-toggle="ratting-component-fill" style="width: 80%"><div class="global-views-star-rating-area-filled"> <i class="fa fa-star"></i><i class="fa fa-star"></i><i class="fa fa-star"></i><i class="fa fa-star"></i><i class="fa fa-star"></i> </div></div></div>   </span> 
<!-- TEMPLATE ENDS: n --></div><br class="clear">  <div class="itemTitle font-14 lh-sm block-with-text"><span class="font--600 font--dark font-spacing-1">Kenmore 20232  3.5 cu. ft. Top-Load Washer with Deep Fill Option - White</span></div><div class="itemPrice"><div data-view="Item.Price"><!-- TEMPLATE STARTS: n-->
 <div class="item-views-price">   <span itemprop="offers" itemscope="" itemtype="http://schema.org/Offer"><link itemprop="availability" href="http://schema.org/OutOfStock"><link itemprop="itemCondition" href="http://schema.org/NewCondition">   <meta itemprop="priceCurrency" content="USD">  <div class="font-12 font--gray1"><span>   <del>$589.99</del>   (List Price) </span></div>   <div class="btn-show-price"><meta itemprop="priceCurrency" content="USD"><meta itemprop="price" content="419.99"><strong class="font--black price-font" data-rate="419.99">  $419.99  </strong>   <span class="font-black plp--title font-14 lh-sm font--text block-with-text">or</span>      <strong data-placement="top" data-toggle="tooltip" title="" data-original-title="To get the leasing price, add the item to your cart and select the 'Lease It' option to checkout">$18.90/week</strong>    </div>       <p class="font-14 font--green block-with-text-1 hidden-xs hidden-sm"><span>You Save: &nbsp;</span><span class="font--green font--600">$170.00</span></p>       </span>    </div> 
<!-- TEMPLATE ENDS: n --></div></div></a><span class="add-to-shopping-list-container padding-vert-md"><button class="btn btn-link bordered--xs bordered--gray2 bg--gray0" data-toggle="tooltip" title="" style="display: none;" data-action="go-to-shopping-list" data-item-id="88120" data-original-title="View shopping list"><i class="fa fa-th-list font--dark" aria-hidden="true"></i></button></span></div>
                                                </div>
                                            </div>
                                            <div class="owl-item active" style="width: 108.667px;">
                                                <div class="merchants-picks-item-wrap">
                                                    <div itemprop="itemListElement" data-item-id="21816" data-track-productlist-list="" data-track-productlist-category="" data-track-productlist-position="" data-sku="026060222000" class="itemWrap padding-horiz-sm"><a href="//product/Kenmore-60222-65-cu-ft-Electric-Dryer-White?preview=4877" data-touchpoint="home" data-hashtag="#/product/Kenmore-60222-65-cu-ft-Electric-Dryer-White?preview=4877"><img data-src="//c.shld.net/rpx/i/s/i/spin/10130653/prod_2041912712?hei=200&amp;wid=200&amp;sharpen=1" alt="026060222000 Kenmore 60222  6.5 cu. ft. Electric Dryer - White" class="owl-lazy img-responsive" style="opacity: 1" src="//c.shld.net/rpx/i/s/i/spin/10130653/prod_2041912712?hei=200&amp;wid=200&amp;sharpen=1"><br>  <div class="font-18 margin-top5" data-view="Global.StarRating"><!-- TEMPLATE STARTS: n-->
<span data-validation="control-group" class="global-columnAttributes">   <span class="text-center" data-toggle="rater" data-validation="control" data-name="" data-max="5" data-value="4.5">   </span>   <div class="global-views-star-rating-area font--review itemReview" data-toggle="rater" data-validation="control" data-name="" data-max="5" data-value="4.5">  <div class="global-views-star-rating-area-empty font--review itemReview"><div class="global-views-star-rating-area-empty-content"> <i class="fa fa-star-o"></i><i class="fa fa-star-o"></i><i class="fa fa-star-o"></i><i class="fa fa-star-o"></i><i class="fa fa-star-o"></i> </div></div>  <div class="global-views-star-rating-area-fill font--review itemReview" data-toggle="ratting-component-fill" style="width: 90%"><div class="global-views-star-rating-area-filled"> <i class="fa fa-star"></i><i class="fa fa-star"></i><i class="fa fa-star"></i><i class="fa fa-star"></i><i class="fa fa-star"></i> </div></div></div>   </span> 
<!-- TEMPLATE ENDS: n --></div><br class="clear">  <div class="itemTitle font-14 lh-sm block-with-text"><span class="font--600 font--dark font-spacing-1">Kenmore 60222  6.5 cu. ft. Electric Dryer - White</span></div><div class="itemPrice"><div data-view="Item.Price"><!-- TEMPLATE STARTS: n-->
 <div class="item-views-price">   <span itemprop="offers" itemscope="" itemtype="http://schema.org/Offer"><link itemprop="availability" href="http://schema.org/OutOfStock"><link itemprop="itemCondition" href="http://schema.org/NewCondition">   <meta itemprop="priceCurrency" content="USD">  <div class="font-12 font--gray1"><span>   <del>$589.99</del>   (List Price) </span></div>   <div class="btn-show-price"><meta itemprop="priceCurrency" content="USD"><meta itemprop="price" content="419.99"><strong class="font--black price-font" data-rate="419.99">  $419.99  </strong>   <span class="font-black plp--title font-14 lh-sm font--text block-with-text">or</span>      <strong data-placement="top" data-toggle="tooltip" title="" data-original-title="To get the leasing price, add the item to your cart and select the 'Lease It' option to checkout">$18.90/week</strong>    </div>       <p class="font-14 font--green block-with-text-1 hidden-xs hidden-sm"><span>You Save: &nbsp;</span><span class="font--green font--600">$170.00</span></p>       </span>    </div> 
<!-- TEMPLATE ENDS: n --></div></div></a><span class="add-to-shopping-list-container padding-vert-md"><button class="btn btn-link bordered--xs bordered--gray2 bg--gray0" data-toggle="tooltip" title="" style="display: none;" data-action="go-to-shopping-list" data-item-id="21816" data-original-title="View shopping list"><i class="fa fa-th-list font--dark" aria-hidden="true"></i></button></span></div>
                                                </div>
                                            </div>
                                            <div class="owl-item active" style="width: 108.667px;">
                                                <div class="merchants-picks-item-wrap">
                                                    <div itemprop="itemListElement" data-item-id="16693" data-track-productlist-list="" data-track-productlist-category="" data-track-productlist-position="" data-sku="022069282000" class="itemWrap padding-horiz-sm"><a href="//product/GE-Appliances-JB250DFWW-53-cu-ft-Freestanding-Electric-Range-White?preview=4877" data-touchpoint="home" data-hashtag="#/product/GE-Appliances-JB250DFWW-53-cu-ft-Freestanding-Electric-Range-White?preview=4877"><img data-src="//c.shld.net/rpx/i/s/i/spin/image/spin_prod_1158165312?hei=200&amp;wid=200&amp;sharpen=1" alt="022069282000 GE Appliances JB250DFWW  5.3 cu. ft. Free-Standing Elec" class="owl-lazy img-responsive" style="opacity: 1" src="//c.shld.net/rpx/i/s/i/spin/image/spin_prod_1158165312?hei=200&amp;wid=200&amp;sharpen=1"><br>  <div class="font-18 margin-top5" data-view="Global.StarRating"><!-- TEMPLATE STARTS: n-->
<span data-validation="control-group" class="global-columnAttributes">   <span class="text-center" data-toggle="rater" data-validation="control" data-name="" data-max="5" data-value="4.5">   </span>   <div class="global-views-star-rating-area font--review itemReview" data-toggle="rater" data-validation="control" data-name="" data-max="5" data-value="4.5">  <div class="global-views-star-rating-area-empty font--review itemReview"><div class="global-views-star-rating-area-empty-content"> <i class="fa fa-star-o"></i><i class="fa fa-star-o"></i><i class="fa fa-star-o"></i><i class="fa fa-star-o"></i><i class="fa fa-star-o"></i> </div></div>  <div class="global-views-star-rating-area-fill font--review itemReview" data-toggle="ratting-component-fill" style="width: 90%"><div class="global-views-star-rating-area-filled"> <i class="fa fa-star"></i><i class="fa fa-star"></i><i class="fa fa-star"></i><i class="fa fa-star"></i><i class="fa fa-star"></i> </div></div></div>   </span> 
<!-- TEMPLATE ENDS: n --></div><br class="clear">  <div class="itemTitle font-14 lh-sm block-with-text"><span class="font--600 font--dark font-spacing-1">GE Appliances JB250DFWW  5.3 cu. ft. Freestanding Electric Range - White</span></div><div class="itemPrice"><div data-view="Item.Price"><!-- TEMPLATE STARTS: n-->
 <div class="item-views-price">   <span itemprop="offers" itemscope="" itemtype="http://schema.org/Offer"><link itemprop="availability" href="http://schema.org/OutOfStock"><link itemprop="itemCondition" href="http://schema.org/NewCondition">   <meta itemprop="priceCurrency" content="USD">  <div class="font-12 font--gray1"><span>   <del>$499.99</del>   (List Price) </span></div>   <div class="btn-show-price"><meta itemprop="priceCurrency" content="USD"><meta itemprop="price" content="399.99"><strong class="font--black price-font" data-rate="399.99">  $399.99  </strong>   <span class="font-black plp--title font-14 lh-sm font--text block-with-text">or</span>      <strong data-placement="top" data-toggle="tooltip" title="" data-original-title="To get the leasing price, add the item to your cart and select the 'Lease It' option to checkout">$18/week</strong>    </div>       <p class="font-14 font--green block-with-text-1 hidden-xs hidden-sm"><span>You Save: &nbsp;</span><span class="font--green font--600">$100.00</span></p>       </span>    </div> 
<!-- TEMPLATE ENDS: n --></div></div></a><span class="add-to-shopping-list-container padding-vert-md"><button class="btn btn-link bordered--xs bordered--gray2 bg--gray0" data-toggle="tooltip" title="" style="display: none;" data-action="go-to-shopping-list" data-item-id="16693" data-original-title="View shopping list"><i class="fa fa-th-list font--dark" aria-hidden="true"></i></button></span></div>
                                                </div>
                                            </div>
                                            <div class="owl-item" style="width: 108.667px;">
                                                <div class="merchants-picks-item-wrap">
                                                    <div itemprop="itemListElement" data-item-id="133016" data-track-productlist-list="" data-track-productlist-category="" data-track-productlist-position="" data-sku="071037460000" class="itemWrap padding-horiz-sm"><a href="//product/Craftsman-37460-21-140cc-Push-Mower-with-High-Rear-Wheels?preview=4877" data-touchpoint="home" data-hashtag="#/product/Craftsman-37460-21-140cc-Push-Mower-with-High-Rear-Wheels?preview=4877"><img data-src="//c.shld.net/rpx/i/s/i/spin/10068794/prod_18973893712?hei=200&amp;wid=200&amp;sharpen=1" alt="071037460000 Craftsman 37460 21&quot;&quot; 140cc Push Mower with High Rear Whe" class="owl-lazy img-responsive" style="opacity: 1"><br>  <div class="font-18 margin-top5" data-view="Global.StarRating"><!-- TEMPLATE STARTS: n-->
<span data-validation="control-group" class="global-columnAttributes">   <span class="text-center" data-toggle="rater" data-validation="control" data-name="" data-max="5" data-value="1">   </span>   <div class="global-views-star-rating-area font--review itemReview" data-toggle="rater" data-validation="control" data-name="" data-max="5" data-value="1">  <div class="global-views-star-rating-area-empty font--review itemReview"><div class="global-views-star-rating-area-empty-content"> <i class="fa fa-star-o"></i><i class="fa fa-star-o"></i><i class="fa fa-star-o"></i><i class="fa fa-star-o"></i><i class="fa fa-star-o"></i> </div></div>  <div class="global-views-star-rating-area-fill font--review itemReview" data-toggle="ratting-component-fill" style="width: 20%"><div class="global-views-star-rating-area-filled"> <i class="fa fa-star"></i><i class="fa fa-star"></i><i class="fa fa-star"></i><i class="fa fa-star"></i><i class="fa fa-star"></i> </div></div></div>   </span> 
<!-- TEMPLATE ENDS: n --></div><br class="clear">  <div class="itemTitle font-14 lh-sm block-with-text"><span class="font--600 font--dark font-spacing-1">Craftsman 37460 21" 140cc Push Mower with High Rear Wheels</span></div><div class="itemPrice"><div data-view="Item.Price"><!-- TEMPLATE STARTS: n-->
 <div class="item-views-price">   <span itemprop="offers" itemscope="" itemtype="http://schema.org/Offer"><link itemprop="availability" href="http://schema.org/OutOfStock"><link itemprop="itemCondition" href="http://schema.org/NewCondition">   <meta itemprop="priceCurrency" content="USD">  <div class="font-12 font--gray1"><span>   <del>$249.99</del>   (List Price) </span></div>   <div class="btn-show-price"><meta itemprop="priceCurrency" content="USD"><meta itemprop="price" content="189.99"><strong class="font--black price-font" data-rate="189.99">  $189.99  </strong>     </div>       <p class="font-14 font--green block-with-text-1 hidden-xs hidden-sm"><span>You Save: &nbsp;</span><span class="font--green font--600">$60.00</span></p>       </span>    </div> 
<!-- TEMPLATE ENDS: n --></div></div></a><span class="add-to-shopping-list-container padding-vert-md"><button class="btn btn-link bordered--xs bordered--gray2 bg--gray0" data-toggle="tooltip" title="" style="display: none;" data-action="go-to-shopping-list" data-item-id="133016" data-original-title="View shopping list"><i class="fa fa-th-list font--dark" aria-hidden="true"></i></button></span></div>
                                                </div>
                                            </div>
                                            <div class="owl-item" style="width: 108.667px;">
                                                <div class="merchants-picks-item-wrap">
                                                    <div itemprop="itemListElement" data-item-id="112661" data-track-productlist-list="" data-track-productlist-category="" data-track-productlist-position="" data-sku="046050043000" class="itemWrap padding-horiz-sm"><a href="//product/Kenmore-50043-25-cu-ft-SidebySide-Refrigerator-with-Ice-Water-Dispenser-Stainless-Steel?preview=4877" data-touchpoint="home" data-hashtag="#/product/Kenmore-50043-25-cu-ft-SidebySide-Refrigerator-with-Ice-Water-Dispenser-Stainless-Steel?preview=4877"><img data-src="//c.shld.net/rpx/i/s/i/spin/10130653/prod_17799782112?hei=200&amp;wid=200&amp;sharpen=1" alt="046050043000 Kenmore 50043 25 cu. ft. Side-by-Side Refrigerator  wit" class="owl-lazy img-responsive" style="opacity: 1"><br>  <div class="font-18 margin-top5" data-view="Global.StarRating"><!-- TEMPLATE STARTS: n-->
<span data-validation="control-group" class="global-columnAttributes">   <span class="text-center" data-toggle="rater" data-validation="control" data-name="" data-max="5" data-value="3.5">   </span>   <div class="global-views-star-rating-area font--review itemReview" data-toggle="rater" data-validation="control" data-name="" data-max="5" data-value="3.5">  <div class="global-views-star-rating-area-empty font--review itemReview"><div class="global-views-star-rating-area-empty-content"> <i class="fa fa-star-o"></i><i class="fa fa-star-o"></i><i class="fa fa-star-o"></i><i class="fa fa-star-o"></i><i class="fa fa-star-o"></i> </div></div>  <div class="global-views-star-rating-area-fill font--review itemReview" data-toggle="ratting-component-fill" style="width: 70%"><div class="global-views-star-rating-area-filled"> <i class="fa fa-star"></i><i class="fa fa-star"></i><i class="fa fa-star"></i><i class="fa fa-star"></i><i class="fa fa-star"></i> </div></div></div>   </span> 
<!-- TEMPLATE ENDS: n --></div><br class="clear">  <div class="itemTitle font-14 lh-sm block-with-text"><span class="font--600 font--dark font-spacing-1">Kenmore 50043 25 cu. ft. Side-by-Side Refrigerator  with Ice &amp; Water Dispenser - Stainless Steel</span></div><div class="itemPrice"><div data-view="Item.Price"><!-- TEMPLATE STARTS: n-->
 <div class="item-views-price">   <span itemprop="offers" itemscope="" itemtype="http://schema.org/Offer"><link itemprop="availability" href="http://schema.org/OutOfStock"><link itemprop="itemCondition" href="http://schema.org/NewCondition">   <meta itemprop="priceCurrency" content="USD">  <div class="font-12 font--gray1"><span>   <del>$1,369.99</del>   (List Price) </span></div>   <div class="btn-show-price"><meta itemprop="priceCurrency" content="USD"><meta itemprop="price" content="899.99"><strong class="font--black price-font" data-rate="899.99">  $899.99  </strong>   <span class="font-black plp--title font-14 lh-sm font--text block-with-text">or</span>      <strong data-placement="top" data-toggle="tooltip" title="" data-original-title="To get the leasing price, add the item to your cart and select the 'Lease It' option to checkout">$40.50/week</strong>    </div>       <p class="font-14 font--green block-with-text-1 hidden-xs hidden-sm"><span>You Save: &nbsp;</span><span class="font--green font--600">$470.00</span></p>       </span>    </div> 
<!-- TEMPLATE ENDS: n --></div></div></a><span class="add-to-shopping-list-container padding-vert-md"><button class="btn btn-link bordered--xs bordered--gray2 bg--gray0" data-toggle="tooltip" title="" style="display: none;" data-action="go-to-shopping-list" data-item-id="112661" data-original-title="View shopping list"><i class="fa fa-th-list font--dark" aria-hidden="true"></i></button></span></div>
                                                </div>
                                            </div>
                                            <div class="owl-item" style="width: 108.667px;">
                                                <div class="merchants-picks-item-wrap">
                                                    <div itemprop="itemListElement" data-item-id="147665" data-track-productlist-list="" data-track-productlist-category="" data-track-productlist-position="" data-sku="022083483000" class="itemWrap padding-horiz-sm"><a href="//product/Samsung-NE59N6630SSAA-59-cu-ft-Freestanding-Electric-Range-with-True-Convection-Stainless-Steel?preview=4877" data-touchpoint="home" data-hashtag="#/product/Samsung-NE59N6630SSAA-59-cu-ft-Freestanding-Electric-Range-with-True-Convection-Stainless-Steel?preview=4877"><img data-src="//c.shld.net/rpx/i/s/i/spin/10103564/prod_19256412412?hei=200&amp;wid=200&amp;sharpen=1" alt="022083483000 Samsung NE59N6630SS/AA 5.9 cu. ft. Freestanding Electri" class="owl-lazy img-responsive" style="opacity: 1"><br>  <div class="font-18 margin-top5" data-view="Global.StarRating"><!-- TEMPLATE STARTS: n-->
<span data-validation="control-group" class="global-columnAttributes">   <span class="text-center" data-toggle="rater" data-validation="control" data-name="" data-max="5" data-value="0">   </span>   <strong class="metaRatingValueForIndividualReviews bg--primary font--light padding--sm border-radius--xl hide">0</strong>   </span> 
<!-- TEMPLATE ENDS: n --></div><br class="clear">  <div class="itemTitle font-14 lh-sm block-with-text"><span class="font--600 font--dark font-spacing-1">Samsung NE59N6630SS/AA 5.9 cu. ft. Freestanding Electric Range with True Convection -Stainless Stee</span></div><div class="itemPrice"><div data-view="Item.Price"><!-- TEMPLATE STARTS: n-->
 <div class="item-views-price">   <span itemprop="offers" itemscope="" itemtype="http://schema.org/Offer"><link itemprop="availability" href="http://schema.org/OutOfStock"><link itemprop="itemCondition" href="http://schema.org/NewCondition">   <meta itemprop="priceCurrency" content="USD">  <div class="font-12 font--gray1"><span>   <del>$999.99</del>   (List Price) </span></div>   <div class="btn-show-price"><meta itemprop="priceCurrency" content="USD"><meta itemprop="price" content="749.99"><strong class="font--black price-font" data-rate="749.99">  $749.99  </strong>   <span class="font-black plp--title font-14 lh-sm font--text block-with-text">or</span>      <strong data-placement="top" data-toggle="tooltip" title="" data-original-title="To get the leasing price, add the item to your cart and select the 'Lease It' option to checkout">$33.75/week</strong>    </div>       <p class="font-14 font--green block-with-text-1 hidden-xs hidden-sm"><span>You Save: &nbsp;</span><span class="font--green font--600">$250.00</span></p>       </span>    </div> 
<!-- TEMPLATE ENDS: n --></div></div></a><span class="add-to-shopping-list-container padding-vert-md"><button class="btn btn-link bordered--xs bordered--gray2 bg--gray0" data-toggle="tooltip" title="" style="display: none;" data-action="go-to-shopping-list" data-item-id="147665" data-original-title="View shopping list"><i class="fa fa-th-list font--dark" aria-hidden="true"></i></button></span></div>
                                                </div>
                                            </div>
                                            <div class="owl-item" style="width: 108.667px;">
                                                <div class="merchants-picks-item-wrap">
                                                    <div itemprop="itemListElement" data-item-id="20617" data-track-productlist-list="" data-track-productlist-category="" data-track-productlist-position="" data-sku="026025132000" class="itemWrap padding-horiz-sm"><a href="//product/Kenmore-25132-43-cu-ft-Top-Load-Washer-w-Exclusive-Triple-Action-Impeller-White?preview=4877" data-touchpoint="home" data-hashtag="#/product/Kenmore-25132-43-cu-ft-Top-Load-Washer-w-Exclusive-Triple-Action-Impeller-White?preview=4877"><img data-src="//c.shld.net/rpx/i/s/i/spin/10130653/prod_18983787712?hei=200&amp;wid=200&amp;sharpen=1" alt="026025132000 Kenmore 25132  4.3 cu. ft. Top Load Washer w/ Exclusive" class="owl-lazy img-responsive" style="opacity: 1"><br>  <div class="font-18 margin-top5" data-view="Global.StarRating"><!-- TEMPLATE STARTS: n-->
<span data-validation="control-group" class="global-columnAttributes">   <span class="text-center" data-toggle="rater" data-validation="control" data-name="" data-max="5" data-value="3.5">   </span>   <div class="global-views-star-rating-area font--review itemReview" data-toggle="rater" data-validation="control" data-name="" data-max="5" data-value="3.5">  <div class="global-views-star-rating-area-empty font--review itemReview"><div class="global-views-star-rating-area-empty-content"> <i class="fa fa-star-o"></i><i class="fa fa-star-o"></i><i class="fa fa-star-o"></i><i class="fa fa-star-o"></i><i class="fa fa-star-o"></i> </div></div>  <div class="global-views-star-rating-area-fill font--review itemReview" data-toggle="ratting-component-fill" style="width: 70%"><div class="global-views-star-rating-area-filled"> <i class="fa fa-star"></i><i class="fa fa-star"></i><i class="fa fa-star"></i><i class="fa fa-star"></i><i class="fa fa-star"></i> </div></div></div>   </span> 
<!-- TEMPLATE ENDS: n --></div><br class="clear">  <div class="itemTitle font-14 lh-sm block-with-text"><span class="font--600 font--dark font-spacing-1">Kenmore 25132  4.3 cu. ft. Top Load Washer w/ Exclusive Triple Action Impeller - White</span></div><div class="itemPrice"><div data-view="Item.Price"><!-- TEMPLATE STARTS: n-->
 <div class="item-views-price">   <span itemprop="offers" itemscope="" itemtype="http://schema.org/Offer"><link itemprop="availability" href="http://schema.org/OutOfStock"><link itemprop="itemCondition" href="http://schema.org/NewCondition">   <meta itemprop="priceCurrency" content="USD">  <div class="font-12 font--gray1"><span>   <del>$839.99</del>   (List Price) </span></div>   <div class="btn-show-price"><meta itemprop="priceCurrency" content="USD"><meta itemprop="price" content="579.99"><strong class="font--black price-font" data-rate="579.99">  $579.99  </strong>   <span class="font-black plp--title font-14 lh-sm font--text block-with-text">or</span>      <strong data-placement="top" data-toggle="tooltip" title="" data-original-title="To get the leasing price, add the item to your cart and select the 'Lease It' option to checkout">$26.10/week</strong>    </div>       <p class="font-14 font--green block-with-text-1 hidden-xs hidden-sm"><span>You Save: &nbsp;</span><span class="font--green font--600">$260.00</span></p>       </span>    </div> 
<!-- TEMPLATE ENDS: n --></div></div></a><span class="add-to-shopping-list-container padding-vert-md"><button class="btn btn-link bordered--xs bordered--gray2 bg--gray0" data-toggle="tooltip" title="" style="display: none;" data-action="go-to-shopping-list" data-item-id="20617" data-original-title="View shopping list"><i class="fa fa-th-list font--dark" aria-hidden="true"></i></button></span></div>
                                                </div>
                                            </div>
                                            <div class="owl-item" style="width: 108.667px;">
                                                <div class="merchants-picks-item-wrap">
                                                    <div itemprop="itemListElement" data-item-id="20618" data-track-productlist-list="" data-track-productlist-category="" data-track-productlist-position="" data-sku="026065132000" class="itemWrap padding-horiz-sm"><a href="//product/Kenmore-65132-70-cu-ft-Electric-Dryer-w-SmartDry-Plus-Technology-White?preview=4877" data-touchpoint="home" data-hashtag="#/product/Kenmore-65132-70-cu-ft-Electric-Dryer-w-SmartDry-Plus-Technology-White?preview=4877"><img data-src="//c.shld.net/rpx/i/s/i/spin/10130653/prod_12126198612?hei=200&amp;wid=200&amp;sharpen=1" alt="026065132000 Kenmore 65132  7.0 cu. ft. Electric Dryer w/ SmartDry P" class="owl-lazy img-responsive" style="opacity: 1"><br>  <div class="font-18 margin-top5" data-view="Global.StarRating"><!-- TEMPLATE STARTS: n-->
<span data-validation="control-group" class="global-columnAttributes">   <span class="text-center" data-toggle="rater" data-validation="control" data-name="" data-max="5" data-value="4">   </span>   <div class="global-views-star-rating-area font--review itemReview" data-toggle="rater" data-validation="control" data-name="" data-max="5" data-value="4">  <div class="global-views-star-rating-area-empty font--review itemReview"><div class="global-views-star-rating-area-empty-content"> <i class="fa fa-star-o"></i><i class="fa fa-star-o"></i><i class="fa fa-star-o"></i><i class="fa fa-star-o"></i><i class="fa fa-star-o"></i> </div></div>  <div class="global-views-star-rating-area-fill font--review itemReview" data-toggle="ratting-component-fill" style="width: 80%"><div class="global-views-star-rating-area-filled"> <i class="fa fa-star"></i><i class="fa fa-star"></i><i class="fa fa-star"></i><i class="fa fa-star"></i><i class="fa fa-star"></i> </div></div></div>   </span> 
<!-- TEMPLATE ENDS: n --></div><br class="clear">  <div class="itemTitle font-14 lh-sm block-with-text"><span class="font--600 font--dark font-spacing-1">Kenmore 65132  7.0 cu. ft. Electric Dryer w/ SmartDry Plus Technology - White</span></div><div class="itemPrice"><div data-view="Item.Price"><!-- TEMPLATE STARTS: n-->
 <div class="item-views-price">   <span itemprop="offers" itemscope="" itemtype="http://schema.org/Offer"><link itemprop="availability" href="http://schema.org/OutOfStock"><link itemprop="itemCondition" href="http://schema.org/NewCondition">   <meta itemprop="priceCurrency" content="USD">  <div class="font-12 font--gray1"><span>   <del>$839.99</del>   (List Price) </span></div>   <div class="btn-show-price"><meta itemprop="priceCurrency" content="USD"><meta itemprop="price" content="579.99"><strong class="font--black price-font" data-rate="579.99">  $579.99  </strong>   <span class="font-black plp--title font-14 lh-sm font--text block-with-text">or</span>      <strong data-placement="top" data-toggle="tooltip" title="" data-original-title="To get the leasing price, add the item to your cart and select the 'Lease It' option to checkout">$26.10/week</strong>    </div>       <p class="font-14 font--green block-with-text-1 hidden-xs hidden-sm"><span>You Save: &nbsp;</span><span class="font--green font--600">$260.00</span></p>       </span>    </div> 
<!-- TEMPLATE ENDS: n --></div></div></a><span class="add-to-shopping-list-container padding-vert-md"><button class="btn btn-link bordered--xs bordered--gray2 bg--gray0" data-toggle="tooltip" title="" style="display: none;" data-action="go-to-shopping-list" data-item-id="20618" data-original-title="View shopping list"><i class="fa fa-th-list font--dark" aria-hidden="true"></i></button></span></div>
                                                </div>
                                            </div>
                                            <div class="owl-item" style="width: 108.667px;">
                                                <div class="merchants-picks-item-wrap">
                                                    <div itemprop="itemListElement" data-item-id="134625" data-track-productlist-list="" data-track-productlist-category="" data-track-productlist-position="" data-sku="071075277000" class="itemWrap padding-horiz-sm"><a href="//product/Craftsman-020698-2700psi-21-GPM-Gas-Pressure-Washer?preview=4877" data-touchpoint="home" data-hashtag="#/product/Craftsman-020698-2700psi-21-GPM-Gas-Pressure-Washer?preview=4877"><img data-src="//c.shld.net/rpx/i/s/i/spin/10047173/prod_19101262412?hei=200&amp;wid=200&amp;sharpen=1" alt="071075277000 Craftsman 020698 2700psi 2.1 GPM Gas Pressure Washer" class="owl-lazy img-responsive" style="opacity: 1"><br>  <div class="font-18 margin-top5" data-view="Global.StarRating"><!-- TEMPLATE STARTS: n-->
<span data-validation="control-group" class="global-columnAttributes">   <span class="text-center" data-toggle="rater" data-validation="control" data-name="" data-max="5" data-value="0">   </span>   <strong class="metaRatingValueForIndividualReviews bg--primary font--light padding--sm border-radius--xl hide">0</strong>   </span> 
<!-- TEMPLATE ENDS: n --></div><br class="clear">  <div class="itemTitle font-14 lh-sm block-with-text"><span class="font--600 font--dark font-spacing-1">Craftsman 020698 2700psi 2.1 GPM Gas Pressure Washer</span></div><div class="itemPrice"><div data-view="Item.Price"><!-- TEMPLATE STARTS: n-->
 <div class="item-views-price">   <span itemprop="offers" itemscope="" itemtype="http://schema.org/Offer"><link itemprop="availability" href="http://schema.org/OutOfStock"><link itemprop="itemCondition" href="http://schema.org/NewCondition">   <meta itemprop="priceCurrency" content="USD">  <div class="font-12 font--gray1"><span>   <del>$369.99</del>   (List Price) </span></div>   <div class="btn-show-price"><meta itemprop="priceCurrency" content="USD"><meta itemprop="price" content="299.99"><strong class="font--black price-font" data-rate="299.99">  $299.99  </strong>   <span class="font-black plp--title font-14 lh-sm font--text block-with-text">or</span>      <strong data-placement="top" data-toggle="tooltip" title="" data-original-title="To get the leasing price, add the item to your cart and select the 'Lease It' option to checkout">$13.50/week</strong>    </div>       <p class="font-14 font--green block-with-text-1 hidden-xs hidden-sm"><span>You Save: &nbsp;</span><span class="font--green font--600">$70.00</span></p>       </span>    </div> 
<!-- TEMPLATE ENDS: n --></div></div></a><span class="add-to-shopping-list-container padding-vert-md"><button class="btn btn-link bordered--xs bordered--gray2 bg--gray0" data-toggle="tooltip" title="" style="display: none;" data-action="go-to-shopping-list" data-item-id="134625" data-original-title="View shopping list"><i class="fa fa-th-list font--dark" aria-hidden="true"></i></button></span></div>
                                                </div>
                                            </div>
                                            <div class="owl-item" style="width: 108.667px;">
                                                <div class="merchants-picks-item-wrap">
                                                    <div itemprop="itemListElement" data-item-id="12047" data-track-productlist-list="" data-track-productlist-category="" data-track-productlist-position="" data-sku="009031794000" class="itemWrap padding-horiz-sm"><a href="//product/Craftsman-31794-17-pc-Screwdriver-Set?preview=4877" data-touchpoint="home" data-hashtag="#/product/Craftsman-31794-17-pc-Screwdriver-Set?preview=4877"><img data-src="//c.shld.net/rpx/i/s/i/spin/image/spin_prod_1159448512?hei=200&amp;wid=200&amp;sharpen=1" alt="009031794000 Craftsman 17 pc. Screwdriver Set" class="owl-lazy img-responsive" style="opacity: 1"><br>  <div class="font-18 margin-top5" data-view="Global.StarRating"><!-- TEMPLATE STARTS: n-->
<span data-validation="control-group" class="global-columnAttributes">   <span class="text-center" data-toggle="rater" data-validation="control" data-name="" data-max="5" data-value="5">   </span>   <div class="global-views-star-rating-area font--review itemReview" data-toggle="rater" data-validation="control" data-name="" data-max="5" data-value="5">  <div class="global-views-star-rating-area-empty font--review itemReview"><div class="global-views-star-rating-area-empty-content"> <i class="fa fa-star-o"></i><i class="fa fa-star-o"></i><i class="fa fa-star-o"></i><i class="fa fa-star-o"></i><i class="fa fa-star-o"></i> </div></div>  <div class="global-views-star-rating-area-fill font--review itemReview" data-toggle="ratting-component-fill" style="width: 100%"><div class="global-views-star-rating-area-filled"> <i class="fa fa-star"></i><i class="fa fa-star"></i><i class="fa fa-star"></i><i class="fa fa-star"></i><i class="fa fa-star"></i> </div></div></div>   </span> 
<!-- TEMPLATE ENDS: n --></div><br class="clear">  <div class="itemTitle font-14 lh-sm block-with-text"><span class="font--600 font--dark font-spacing-1">Craftsman 31794 17 pc. Screwdriver Set</span></div><div class="itemPrice"><div data-view="Item.Price"><!-- TEMPLATE STARTS: n-->
 <div class="item-views-price">   <span itemprop="offers" itemscope="" itemtype="http://schema.org/Offer"><link itemprop="availability" href="http://schema.org/OutOfStock"><link itemprop="itemCondition" href="http://schema.org/NewCondition">   <meta itemprop="priceCurrency" content="USD">  <div class="font-12 font--gray1"><span>   <del>$34.99</del>   (List Price) </span></div>   <div class="btn-show-price"><meta itemprop="priceCurrency" content="USD"><meta itemprop="price" content="29.99"><strong class="font--black price-font" data-rate="29.99">  $29.99  </strong>     </div>       <p class="font-14 font--green block-with-text-1 hidden-xs hidden-sm"><span>You Save: &nbsp;</span><span class="font--green font--600">$5.00</span></p>       </span>    </div> 
<!-- TEMPLATE ENDS: n --></div></div></a><span class="add-to-shopping-list-container padding-vert-md"><button class="btn btn-link bordered--xs bordered--gray2 bg--gray0" data-toggle="tooltip" title="" style="display: none;" data-action="go-to-shopping-list" data-item-id="12047" data-original-title="View shopping list"><i class="fa fa-th-list font--dark" aria-hidden="true"></i></button></span></div>
                                                </div>
                                            </div>
                                            <div class="owl-item cloned" style="width: 108.667px;">
                                                <div class="merchants-picks-item-wrap">
                                                    <div itemprop="itemListElement" data-item-id="88120" data-track-productlist-list="" data-track-productlist-category="" data-track-productlist-position="" data-sku="026020232000" class="itemWrap padding-horiz-sm"><a href="//product/Kenmore-20232-35-cu-ft-TopLoad-Washer-with-Deep-Fill-Option-White?preview=4877" data-touchpoint="home" data-hashtag="#/product/Kenmore-20232-35-cu-ft-TopLoad-Washer-with-Deep-Fill-Option-White?preview=4877"><img data-src="//c.shld.net/rpx/i/s/i/spin/10130653/prod_16327306112?hei=200&amp;wid=200&amp;sharpen=1" alt="026020232000 Kenmore 20232  3.5 cu. ft. Top-Load Washer with Deep Fi" class="owl-lazy img-responsive" style="opacity: 1" src="//c.shld.net/rpx/i/s/i/spin/10130653/prod_16327306112?hei=200&amp;wid=200&amp;sharpen=1"><br>  <div class="font-18 margin-top5" data-view="Global.StarRating"><!-- TEMPLATE STARTS: n-->
<span data-validation="control-group" class="global-columnAttributes">   <span class="text-center" data-toggle="rater" data-validation="control" data-name="" data-max="5" data-value="4">   </span>   <div class="global-views-star-rating-area font--review itemReview" data-toggle="rater" data-validation="control" data-name="" data-max="5" data-value="4">  <div class="global-views-star-rating-area-empty font--review itemReview"><div class="global-views-star-rating-area-empty-content"> <i class="fa fa-star-o"></i><i class="fa fa-star-o"></i><i class="fa fa-star-o"></i><i class="fa fa-star-o"></i><i class="fa fa-star-o"></i> </div></div>  <div class="global-views-star-rating-area-fill font--review itemReview" data-toggle="ratting-component-fill" style="width: 80%"><div class="global-views-star-rating-area-filled"> <i class="fa fa-star"></i><i class="fa fa-star"></i><i class="fa fa-star"></i><i class="fa fa-star"></i><i class="fa fa-star"></i> </div></div></div>   </span> 
<!-- TEMPLATE ENDS: n --></div><br class="clear">  <div class="itemTitle font-14 lh-sm block-with-text"><span class="font--600 font--dark font-spacing-1">Kenmore 20232  3.5 cu. ft. Top-Load Washer with Deep Fill Option - White</span></div><div class="itemPrice"><div data-view="Item.Price"><!-- TEMPLATE STARTS: n-->
 <div class="item-views-price">   <span itemprop="offers" itemscope="" itemtype="http://schema.org/Offer"><link itemprop="availability" href="http://schema.org/OutOfStock"><link itemprop="itemCondition" href="http://schema.org/NewCondition">   <meta itemprop="priceCurrency" content="USD">  <div class="font-12 font--gray1"><span>   <del>$589.99</del>   (List Price) </span></div>   <div class="btn-show-price"><meta itemprop="priceCurrency" content="USD"><meta itemprop="price" content="419.99"><strong class="font--black price-font" data-rate="419.99">  $419.99  </strong>   <span class="font-black plp--title font-14 lh-sm font--text block-with-text">or</span>      <strong data-placement="top" data-toggle="tooltip" title="" data-original-title="To get the leasing price, add the item to your cart and select the 'Lease It' option to checkout">$18.90/week</strong>    </div>       <p class="font-14 font--green block-with-text-1 hidden-xs hidden-sm"><span>You Save: &nbsp;</span><span class="font--green font--600">$170.00</span></p>       </span>    </div> 
<!-- TEMPLATE ENDS: n --></div></div></a><span class="add-to-shopping-list-container padding-vert-md"><button class="btn btn-link bordered--xs bordered--gray2 bg--gray0" data-toggle="tooltip" title="" style="display: none;" data-action="go-to-shopping-list" data-item-id="88120" data-original-title="View shopping list"><i class="fa fa-th-list font--dark" aria-hidden="true"></i></button></span></div>
                                                </div>
                                            </div>
                                            <div class="owl-item cloned" style="width: 108.667px;">
                                                <div class="merchants-picks-item-wrap">
                                                    <div itemprop="itemListElement" data-item-id="21816" data-track-productlist-list="" data-track-productlist-category="" data-track-productlist-position="" data-sku="026060222000" class="itemWrap padding-horiz-sm"><a href="//product/Kenmore-60222-65-cu-ft-Electric-Dryer-White?preview=4877" data-touchpoint="home" data-hashtag="#/product/Kenmore-60222-65-cu-ft-Electric-Dryer-White?preview=4877"><img data-src="//c.shld.net/rpx/i/s/i/spin/10130653/prod_2041912712?hei=200&amp;wid=200&amp;sharpen=1" alt="026060222000 Kenmore 60222  6.5 cu. ft. Electric Dryer - White" class="owl-lazy img-responsive" style="opacity: 1" src="//c.shld.net/rpx/i/s/i/spin/10130653/prod_2041912712?hei=200&amp;wid=200&amp;sharpen=1"><br>  <div class="font-18 margin-top5" data-view="Global.StarRating"><!-- TEMPLATE STARTS: n-->
<span data-validation="control-group" class="global-columnAttributes">   <span class="text-center" data-toggle="rater" data-validation="control" data-name="" data-max="5" data-value="4.5">   </span>   <div class="global-views-star-rating-area font--review itemReview" data-toggle="rater" data-validation="control" data-name="" data-max="5" data-value="4.5">  <div class="global-views-star-rating-area-empty font--review itemReview"><div class="global-views-star-rating-area-empty-content"> <i class="fa fa-star-o"></i><i class="fa fa-star-o"></i><i class="fa fa-star-o"></i><i class="fa fa-star-o"></i><i class="fa fa-star-o"></i> </div></div>  <div class="global-views-star-rating-area-fill font--review itemReview" data-toggle="ratting-component-fill" style="width: 90%"><div class="global-views-star-rating-area-filled"> <i class="fa fa-star"></i><i class="fa fa-star"></i><i class="fa fa-star"></i><i class="fa fa-star"></i><i class="fa fa-star"></i> </div></div></div>   </span> 
<!-- TEMPLATE ENDS: n --></div><br class="clear">  <div class="itemTitle font-14 lh-sm block-with-text"><span class="font--600 font--dark font-spacing-1">Kenmore 60222  6.5 cu. ft. Electric Dryer - White</span></div><div class="itemPrice"><div data-view="Item.Price"><!-- TEMPLATE STARTS: n-->
 <div class="item-views-price">   <span itemprop="offers" itemscope="" itemtype="http://schema.org/Offer"><link itemprop="availability" href="http://schema.org/OutOfStock"><link itemprop="itemCondition" href="http://schema.org/NewCondition">   <meta itemprop="priceCurrency" content="USD">  <div class="font-12 font--gray1"><span>   <del>$589.99</del>   (List Price) </span></div>   <div class="btn-show-price"><meta itemprop="priceCurrency" content="USD"><meta itemprop="price" content="419.99"><strong class="font--black price-font" data-rate="419.99">  $419.99  </strong>   <span class="font-black plp--title font-14 lh-sm font--text block-with-text">or</span>      <strong data-placement="top" data-toggle="tooltip" title="" data-original-title="To get the leasing price, add the item to your cart and select the 'Lease It' option to checkout">$18.90/week</strong>    </div>       <p class="font-14 font--green block-with-text-1 hidden-xs hidden-sm"><span>You Save: &nbsp;</span><span class="font--green font--600">$170.00</span></p>       </span>    </div> 
<!-- TEMPLATE ENDS: n --></div></div></a><span class="add-to-shopping-list-container padding-vert-md"><button class="btn btn-link bordered--xs bordered--gray2 bg--gray0" data-toggle="tooltip" title="" style="display: none;" data-action="go-to-shopping-list" data-item-id="21816" data-original-title="View shopping list"><i class="fa fa-th-list font--dark" aria-hidden="true"></i></button></span></div>
                                                </div>
                                            </div>
                                            <div class="owl-item cloned" style="width: 108.667px;">
                                                <div class="merchants-picks-item-wrap">
                                                    <div itemprop="itemListElement" data-item-id="16693" data-track-productlist-list="" data-track-productlist-category="" data-track-productlist-position="" data-sku="022069282000" class="itemWrap padding-horiz-sm"><a href="//product/GE-Appliances-JB250DFWW-53-cu-ft-Freestanding-Electric-Range-White?preview=4877" data-touchpoint="home" data-hashtag="#/product/GE-Appliances-JB250DFWW-53-cu-ft-Freestanding-Electric-Range-White?preview=4877"><img data-src="//c.shld.net/rpx/i/s/i/spin/image/spin_prod_1158165312?hei=200&amp;wid=200&amp;sharpen=1" alt="022069282000 GE Appliances JB250DFWW  5.3 cu. ft. Free-Standing Elec" class="owl-lazy img-responsive" style="opacity: 1" src="//c.shld.net/rpx/i/s/i/spin/image/spin_prod_1158165312?hei=200&amp;wid=200&amp;sharpen=1"><br>  <div class="font-18 margin-top5" data-view="Global.StarRating"><!-- TEMPLATE STARTS: n-->
<span data-validation="control-group" class="global-columnAttributes">   <span class="text-center" data-toggle="rater" data-validation="control" data-name="" data-max="5" data-value="4.5">   </span>   <div class="global-views-star-rating-area font--review itemReview" data-toggle="rater" data-validation="control" data-name="" data-max="5" data-value="4.5">  <div class="global-views-star-rating-area-empty font--review itemReview"><div class="global-views-star-rating-area-empty-content"> <i class="fa fa-star-o"></i><i class="fa fa-star-o"></i><i class="fa fa-star-o"></i><i class="fa fa-star-o"></i><i class="fa fa-star-o"></i> </div></div>  <div class="global-views-star-rating-area-fill font--review itemReview" data-toggle="ratting-component-fill" style="width: 90%"><div class="global-views-star-rating-area-filled"> <i class="fa fa-star"></i><i class="fa fa-star"></i><i class="fa fa-star"></i><i class="fa fa-star"></i><i class="fa fa-star"></i> </div></div></div>   </span> 
<!-- TEMPLATE ENDS: n --></div><br class="clear">  <div class="itemTitle font-14 lh-sm block-with-text"><span class="font--600 font--dark font-spacing-1">GE Appliances JB250DFWW  5.3 cu. ft. Freestanding Electric Range - White</span></div><div class="itemPrice"><div data-view="Item.Price"><!-- TEMPLATE STARTS: n-->
 <div class="item-views-price">   <span itemprop="offers" itemscope="" itemtype="http://schema.org/Offer"><link itemprop="availability" href="http://schema.org/OutOfStock"><link itemprop="itemCondition" href="http://schema.org/NewCondition">   <meta itemprop="priceCurrency" content="USD">  <div class="font-12 font--gray1"><span>   <del>$499.99</del>   (List Price) </span></div>   <div class="btn-show-price"><meta itemprop="priceCurrency" content="USD"><meta itemprop="price" content="399.99"><strong class="font--black price-font" data-rate="399.99">  $399.99  </strong>   <span class="font-black plp--title font-14 lh-sm font--text block-with-text">or</span>      <strong data-placement="top" data-toggle="tooltip" title="" data-original-title="To get the leasing price, add the item to your cart and select the 'Lease It' option to checkout">$18/week</strong>    </div>       <p class="font-14 font--green block-with-text-1 hidden-xs hidden-sm"><span>You Save: &nbsp;</span><span class="font--green font--600">$100.00</span></p>       </span>    </div> 
<!-- TEMPLATE ENDS: n --></div></div></a><span class="add-to-shopping-list-container padding-vert-md"><button class="btn btn-link bordered--xs bordered--gray2 bg--gray0" data-toggle="tooltip" title="" style="display: none;" data-action="go-to-shopping-list" data-item-id="16693" data-original-title="View shopping list"><i class="fa fa-th-list font--dark" aria-hidden="true"></i></button></span></div>
                                                </div>
                                            </div>
                                            <div class="owl-item cloned" style="width: 108.667px;">
                                                <div class="merchants-picks-item-wrap">
                                                    <div itemprop="itemListElement" data-item-id="133016" data-track-productlist-list="" data-track-productlist-category="" data-track-productlist-position="" data-sku="071037460000" class="itemWrap padding-horiz-sm"><a href="//product/Craftsman-37460-21-140cc-Push-Mower-with-High-Rear-Wheels?preview=4877" data-touchpoint="home" data-hashtag="#/product/Craftsman-37460-21-140cc-Push-Mower-with-High-Rear-Wheels?preview=4877"><img data-src="//c.shld.net/rpx/i/s/i/spin/10068794/prod_18973893712?hei=200&amp;wid=200&amp;sharpen=1" alt="071037460000 Craftsman 37460 21&quot;&quot; 140cc Push Mower with High Rear Whe" class="owl-lazy img-responsive" style="opacity: 1"><br>  <div class="font-18 margin-top5" data-view="Global.StarRating"><!-- TEMPLATE STARTS: n-->
<span data-validation="control-group" class="global-columnAttributes">   <span class="text-center" data-toggle="rater" data-validation="control" data-name="" data-max="5" data-value="1">   </span>   <div class="global-views-star-rating-area font--review itemReview" data-toggle="rater" data-validation="control" data-name="" data-max="5" data-value="1">  <div class="global-views-star-rating-area-empty font--review itemReview"><div class="global-views-star-rating-area-empty-content"> <i class="fa fa-star-o"></i><i class="fa fa-star-o"></i><i class="fa fa-star-o"></i><i class="fa fa-star-o"></i><i class="fa fa-star-o"></i> </div></div>  <div class="global-views-star-rating-area-fill font--review itemReview" data-toggle="ratting-component-fill" style="width: 20%"><div class="global-views-star-rating-area-filled"> <i class="fa fa-star"></i><i class="fa fa-star"></i><i class="fa fa-star"></i><i class="fa fa-star"></i><i class="fa fa-star"></i> </div></div></div>   </span> 
<!-- TEMPLATE ENDS: n --></div><br class="clear">  <div class="itemTitle font-14 lh-sm block-with-text"><span class="font--600 font--dark font-spacing-1">Craftsman 37460 21" 140cc Push Mower with High Rear Wheels</span></div><div class="itemPrice"><div data-view="Item.Price"><!-- TEMPLATE STARTS: n-->
 <div class="item-views-price">   <span itemprop="offers" itemscope="" itemtype="http://schema.org/Offer"><link itemprop="availability" href="http://schema.org/OutOfStock"><link itemprop="itemCondition" href="http://schema.org/NewCondition">   <meta itemprop="priceCurrency" content="USD">  <div class="font-12 font--gray1"><span>   <del>$249.99</del>   (List Price) </span></div>   <div class="btn-show-price"><meta itemprop="priceCurrency" content="USD"><meta itemprop="price" content="189.99"><strong class="font--black price-font" data-rate="189.99">  $189.99  </strong>     </div>       <p class="font-14 font--green block-with-text-1 hidden-xs hidden-sm"><span>You Save: &nbsp;</span><span class="font--green font--600">$60.00</span></p>       </span>    </div> 
<!-- TEMPLATE ENDS: n --></div></div></a><span class="add-to-shopping-list-container padding-vert-md"><button class="btn btn-link bordered--xs bordered--gray2 bg--gray0" data-toggle="tooltip" title="" style="display: none;" data-action="go-to-shopping-list" data-item-id="133016" data-original-title="View shopping list"><i class="fa fa-th-list font--dark" aria-hidden="true"></i></button></span></div>
                                                </div>
                                            </div>
                                            <div class="owl-item cloned" style="width: 108.667px;">
                                                <div class="merchants-picks-item-wrap">
                                                    <div itemprop="itemListElement" data-item-id="112661" data-track-productlist-list="" data-track-productlist-category="" data-track-productlist-position="" data-sku="046050043000" class="itemWrap padding-horiz-sm"><a href="//product/Kenmore-50043-25-cu-ft-SidebySide-Refrigerator-with-Ice-Water-Dispenser-Stainless-Steel?preview=4877" data-touchpoint="home" data-hashtag="#/product/Kenmore-50043-25-cu-ft-SidebySide-Refrigerator-with-Ice-Water-Dispenser-Stainless-Steel?preview=4877"><img data-src="//c.shld.net/rpx/i/s/i/spin/10130653/prod_17799782112?hei=200&amp;wid=200&amp;sharpen=1" alt="046050043000 Kenmore 50043 25 cu. ft. Side-by-Side Refrigerator  wit" class="owl-lazy img-responsive" style="opacity: 1"><br>  <div class="font-18 margin-top5" data-view="Global.StarRating"><!-- TEMPLATE STARTS: n-->
<span data-validation="control-group" class="global-columnAttributes">   <span class="text-center" data-toggle="rater" data-validation="control" data-name="" data-max="5" data-value="3.5">   </span>   <div class="global-views-star-rating-area font--review itemReview" data-toggle="rater" data-validation="control" data-name="" data-max="5" data-value="3.5">  <div class="global-views-star-rating-area-empty font--review itemReview"><div class="global-views-star-rating-area-empty-content"> <i class="fa fa-star-o"></i><i class="fa fa-star-o"></i><i class="fa fa-star-o"></i><i class="fa fa-star-o"></i><i class="fa fa-star-o"></i> </div></div>  <div class="global-views-star-rating-area-fill font--review itemReview" data-toggle="ratting-component-fill" style="width: 70%"><div class="global-views-star-rating-area-filled"> <i class="fa fa-star"></i><i class="fa fa-star"></i><i class="fa fa-star"></i><i class="fa fa-star"></i><i class="fa fa-star"></i> </div></div></div>   </span> 
<!-- TEMPLATE ENDS: n --></div><br class="clear">  <div class="itemTitle font-14 lh-sm block-with-text"><span class="font--600 font--dark font-spacing-1">Kenmore 50043 25 cu. ft. Side-by-Side Refrigerator  with Ice &amp; Water Dispenser - Stainless Steel</span></div><div class="itemPrice"><div data-view="Item.Price"><!-- TEMPLATE STARTS: n-->
 <div class="item-views-price">   <span itemprop="offers" itemscope="" itemtype="http://schema.org/Offer"><link itemprop="availability" href="http://schema.org/OutOfStock"><link itemprop="itemCondition" href="http://schema.org/NewCondition">   <meta itemprop="priceCurrency" content="USD">  <div class="font-12 font--gray1"><span>   <del>$1,369.99</del>   (List Price) </span></div>   <div class="btn-show-price"><meta itemprop="priceCurrency" content="USD"><meta itemprop="price" content="899.99"><strong class="font--black price-font" data-rate="899.99">  $899.99  </strong>   <span class="font-black plp--title font-14 lh-sm font--text block-with-text">or</span>      <strong data-placement="top" data-toggle="tooltip" title="" data-original-title="To get the leasing price, add the item to your cart and select the 'Lease It' option to checkout">$40.50/week</strong>    </div>       <p class="font-14 font--green block-with-text-1 hidden-xs hidden-sm"><span>You Save: &nbsp;</span><span class="font--green font--600">$470.00</span></p>       </span>    </div> 
<!-- TEMPLATE ENDS: n --></div></div></a><span class="add-to-shopping-list-container padding-vert-md"><button class="btn btn-link bordered--xs bordered--gray2 bg--gray0" data-toggle="tooltip" title="" style="display: none;" data-action="go-to-shopping-list" data-item-id="112661" data-original-title="View shopping list"><i class="fa fa-th-list font--dark" aria-hidden="true"></i></button></span></div>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="owl-nav">
                                        <div class="owl-prev"><i class="fa fa-chevron-left"></i></div>
                                        <div class="owl-next"><i class="fa fa-chevron-right"></i></div>
                                    </div>
                                    <div class="owl-dots">
                                        <div class="owl-dot active"><span></span></div>
                                        <div class="owl-dot"><span></span></div>
                                        <div class="owl-dot"><span></span></div>
                                        <div class="owl-dot"><span></span></div>
                                    </div>
                                </div>
                            </aside>
                            <!-- TEMPLATE ENDS: n -->
                        </aside>
                        <!-- END #merchantPicks2 -->
